name: games

services:
  postgres:
    image: postgres:16.11-alpine
    container_name: games-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 54321:5432

  dbgate:
    image: dbgate/dbgate
    container_name: games-dbgate
    restart: unless-stopped
    environment:
      CONNECTIONS: con1
      LABEL_con1: Postgres
      SERVER_con1: postgres
      USER_con1: postgres
      PASSWORD_con1: postgres
      PORT_con1: 5432
      ENGINE_con1: postgres@dbgate-plugin-postgres
    ports:
      - "54322:3000"
    depends_on:
      - postgres
